import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Leaf,Send,Database,ArrowRight,CheckCircle2,Clock3,ShieldCheck,Sparkles} from 'lucide-react';
import './index.css';

const demo={
 site_state:{soil_organic_carbon:{value:'low',confidence:.8},water_holding_capacity:{value:'poor',confidence:.8},associated_biodiversity:{value:'low',confidence:.8},biome:{value:'cropland',confidence:.8}},
 deficiencies:[{metric:'soil_organic_carbon',metric_name:'Soil organic carbon stock',severity:'deficient',value:'low'},{metric:'water_holding_capacity',metric_name:'Water Holding Capacity',severity:'deficient',value:'poor'},{metric:'associated_biodiversity',metric_name:'Associated biodiversity',severity:'deficient',value:'low'}],
 recommendations:[
  {intervention:'Cover crops',metric_coverage:3,supporting_metrics:['Soil organic carbon stock','Water Holding Capacity','Associated biodiversity'],causal_effects:[{metric:'Soil organic carbon stock',direction:'increases',effect:'+331 kg C ha⁻¹ yr⁻¹',source:'S02'},{metric:'Associated biodiversity',direction:'increases',effect:'+21%',source:'S13'}],sources:['S02','S13'],time_horizon:'1–3 seasons'},
  {intervention:'Crop diversification',metric_coverage:2,supporting_metrics:['Associated biodiversity','Agricultural production'],causal_effects:[{metric:'Associated biodiversity',direction:'increases',effect:'+67% of effects positive',source:'S21'}],sources:['S13','S21'],time_horizon:'1–3 years'}
 ]
};
function App(){const [q,setQ]=useState('My field has low soil carbon, poor water retention, and low biodiversity.');const [data,setData]=useState(demo);const [loading,setLoading]=useState(false);const ask=async()=>{if(!q.trim())return;setLoading(true);try{const r=await fetch('http://localhost:8000/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});if(!r.ok)throw Error();const x=await r.json();setData(x.analysis||demo)}catch(e){setData(demo)}finally{setLoading(false)}};return <div className="app"><header><div className="brand"><div className="logo"><Leaf size={22}/></div><div><b>Darukaa<span>.Earth</span></b><small>CAUSAL EVIDENCE ENGINE</small></div></div><div className="status"><span/> Evidence-grounded</div></header><main><section className="hero"><div className="eyebrow"><Sparkles size={15}/> AI Environmental Scientist</div><h1>Turn field observations<br/><em>into causal decisions.</em></h1><p>Describe your field conditions. CEE connects environmental variables through scientific evidence instead of generating generic advice.</p><div className="query"><textarea value={q} onChange={e=>setQ(e.target.value)}/><button onClick={ask} disabled={loading}>{loading?'...':<Send size={18}/>}</button></div><div className="chips"><span>Soil</span><span>Water</span><span>Biodiversity</span><span>Evidence + provenance</span></div></section>
<section className="grid"><div className="panel"><div className="panelhead"><div><small>01 · SITE STATE</small><h2>Detected conditions</h2></div><ShieldCheck size={20}/></div><div className="metrics">{Object.entries(data.site_state||{}).map(([k,v])=><div className="metric" key={k}><div className="metricicon">{k.includes('soil')?'S':k.includes('water')?'W':k.includes('bio')?'B':'◈'}</div><div><b>{(v?.value??v)}</b><small>{k.replaceAll('_',' ')}</small></div><span>{Math.round((v?.confidence??.8)*100)}%</span></div>)}</div></div>
<div className="panel"><div className="panelhead"><div><small>02 · DEFICIENCY ANALYSIS</small><h2>What needs attention</h2></div><Database size={20}/></div><div className="deficits">{(data.deficiencies||[]).map(d=><div className="deficit" key={d.metric}><div><b>{d.metric_name}</b><small>{d.value} · {d.severity}</small></div><div className="dot"/></div>)}</div></div></section>
<section className="recommend"><div className="panelhead"><div><small>03 · CAUSAL REASONING</small><h2>Evidence-backed pathways</h2></div><span className="pill">GRAPH + VECTOR RETRIEVAL</span></div><div className="cards">{(data.recommendations||[]).map((r,i)=><article className="rec" key={r.intervention}><div className="recnum">0{i+1}</div><div className="recbody"><div className="rectop"><h3>{r.intervention}</h3><span>{r.metric_coverage} metrics connected</span></div><div className="path">{(r.supporting_metrics||[]).map((m,j)=><React.Fragment key={m}><span>{m}</span>{j<(r.supporting_metrics||[]).length-1&&<ArrowRight size={14}/>}</React.Fragment>)}</div><div className="effects">{(r.causal_effects||[]).map((e,j)=><div key={j}><CheckCircle2 size={15}/><span><b>{e.metric}</b> {e.effect} · {e.source}</span></div>)}</div><footer><span><Clock3 size={14}/> {r.time_horizon||'Context dependent'}</span><span>Sources: {(r.sources||[]).join(', ')}</span></footer></div></article>)}</div></section>
<div className="foot"><span>CEE separates evidence from inference.</span><span>Scientific sources · provenance · multi-metric reasoning</span></div></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
